public class Main {
    public static void main(String[] args){
            String nome = "Savalo";
            String sobrenome = "Horse";
            int idade = 85;
            double altura = 1.80;
            boolean empregado = true;
            String telefone = "40028922";
            String endereco = "de baixo da ponte";
            String cep = "999666";
            String cidade = "Uberlandia";
            String uf = "Minas Gerais";
            double salario = 10.01;
            double hora_extra = 1.1;

            
        System.out.println("nome do aluno:" + nome +" "+ sobrenome);
        System.out.println("Idade:" + idade);
        System.out.println("altura: " + altura);
        System.out.println("Empregado: " + empregado);
        System.out.println("telefone: " + telefone);
        System.out.println("endereco: " + endereco);
        System.out.println("cep: " + cep);
        System.out.println("cidade: " + cidade);
        System.out.println("UF: " + uf);
        System.out.println("salario: " + salario);
        System.out.println("hora extra: " + hora_extra);




}

}